operations:
  view:
    - type: web
      impl: index.html
actions: actions
web: web-src
runtimeManifest:
  packages:
    dx-excshell-1:
      license: Apache-2.0
      actions:
        generic:
          function: actions/generic/index.js
          web: 'yes'
          runtime: nodejs:18
          inputs:
            LOG_LEVEL: debug
          annotations:
            require-adobe-auth: true
            final: true
        forwardevent:
          function: actions/forwardevent/index.js
          web: 'yes'
          runtime: nodejs:18
          inputs:
            LOG_LEVEL: debug
            AWS_ENDPOINT: $AWS_ENDPOINT
            AWS_REGION: $AWS_REGION
            AWS_DEFAULT_AUTH_MODE: $AWS_DEFAULT_AUTH_MODE
            AWS_APIKEY: $AWS_APIKEY
          annotations:
            require-adobe-auth: true
            final: true
